image: docker:stable

stages:
    - Build e Push image
    - Documentation

before_script:
    - apk add bash
    - echo "Read Environment Variable from .env file"
    - source ./.env
    - export JOB_NGINX_VERSION=${CI_NGINX_VERSION:-"$NGINX_VERSION"}
    - export JOB_NGINX_VERSION_DATE=${CI_NGINX_VERSION_DATE:-"$NGINX_VERSION_DATE"}
    - export JOB_MAXMIND_VERSION=${CI_MAXMIND_VERSION:-"$MAXMIND_VERSION"}

update readme:
    stage: Documentation
    variables:
        DOCKERHUB_USERNAME: "$DOCKER_HUB_USER"
        DOCKERHUB_PASSWORD: "$DOCKER_HUB_PASSWORD"
        DOCKERHUB_REPO_PREFIX: "maurosoft1973"
        DOCKERHUB_REPO_NAME: "alpine-nginx"
        DOCKERHUB_SHORT_DESCRIPTION: "Nginx Docker image running on Alpine Linux"
    only:
        - master
    script:
        - LATEST_UPDATE=$(date +"%d.%m.%Y %H:%M:%S")
        - echo "Generate README for Version ${MARIADB_VERSION}"
        - sed "s/\%ALPINE_VERSION\%/${ALPINE_VERSION}/g" README.tpl > README.md1
        - sed "s/\%ALPINE_VERSION_DATE\%/${ALPINE_VERSION_DATE}/g" README.md1 > README.md2
        - sed "s/\%NGINX_VERSION\%/${NGINX_VERSION}/g" README.md2 > README.md3
        - sed "s/\%NGINX_VERSION_DATE\%/${NGINX_VERSION_DATE}/g" README.md3 > README.md4
        - sed "s/\%MAXMIND_VERSION\%/${MAXMIND_VERSION}/g" README.md4 > README.md5
        - sed "s/\%LATEST_UPDATE\%/${LATEST_UPDATE}/g" README.md5 > README.md
        - FULL_DESCRIPTION=$(if [ -f "$(pwd)/README.md" ]; then cat "$(pwd)/README.md"; else echo ""; fi)
        - docker pull maurosoft1973/alpine-readme-to-dockerhub
        - docker run --rm -e DOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -e DOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" -e DOCKERHUB_REPO_PREFIX="$DOCKERHUB_REPO_PREFIX" -e DOCKERHUB_REPO_NAME="$DOCKERHUB_REPO_NAME" -e SHORT_DESCRIPTION="$DOCKERHUB_SHORT_DESCRIPTION" -e FULL_DESCRIPTION="$FULL_DESCRIPTION" maurosoft1973/alpine-readme-to-dockerhub

amd64 test build:
    image: docker
    stage: Build e Push image
    only:
        - master
    variables:
        RELEASE: "TEST"
    script:
        - bash ./build-image.sh -av=$ALPINE_VERSION -avd=$ALPINE_VERSION_DATE -nv=$JOB_NGINX_VERSION -nvd=$JOB_NGINX_VERSION_DATE -mv=$JOB_MAXMIND_VERSION -r=$RELEASE

amd64 current build:
    stage: Build e Push image
    variables:
        RELEASE: "CURRENT"
    only:
        - master
    script:
        - bash ./build-image.sh -av=$ALPINE_VERSION -avd=$ALPINE_VERSION_DATE -nv=$JOB_NGINX_VERSION -nvd=$JOB_NGINX_VERSION_DATE -mv=$JOB_MAXMIND_VERSION -r=$RELEASE

amd64 latest build:
    stage: Build e Push image
    variables:
        RELEASE: "LATEST"
    only:
        - master
    script:
        - bash ./build-image.sh -av=$ALPINE_VERSION -avd=$ALPINE_VERSION_DATE -nv=$JOB_NGINX_VERSION -nvd=$JOB_NGINX_VERSION_DATE -mv=$JOB_MAXMIND_VERSION -r=$RELEASE

