image: docker:stable

stages:
  - Build e Push image
  - Documentation

update readme:
  stage: Documentation
  variables:
    DOCKERHUB_USERNAME: "$DOCKER_HUB_USER"
    DOCKERHUB_PASSWORD: "$DOCKER_HUB_PASSWORD"
    DOCKERHUB_REPO_PREFIX: "maurosoft1973"
    DOCKERHUB_REPO_NAME: "alpine-nginx"
  only:
  - master
  script:
  - FULL_DESCRIPTION=$(if [ -f "$(pwd)/README.md" ]; then cat "$(pwd)/README.md"; else echo ""; fi)
  - docker run --rm -e DOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -e DOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" -e DOCKERHUB_REPO_PREFIX="$DOCKERHUB_REPO_PREFIX" -e DOCKERHUB_REPO_NAME="$DOCKERHUB_REPO_NAME" -e SHORT_DESCRIPTION="Nginx Docker image running on Alpine Linux" -e FULL_DESCRIPTION="$FULL_DESCRIPTION" maurosoft1973/alpine-readme-to-dockerhub

latest build:
  stage: Build e Push image
  only:
  - master
  script:
  - BUILD_DATE=$(date +"%Y-%m-%d")
  - docker build --build-arg BUILD_DATE=$BUILD_DATE -t maurosoft1973/alpine-nginx -t maurosoft1973/alpine-nginx:amd64 -t maurosoft1973/alpine-nginx:x86_64 .
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  - docker push maurosoft1973/alpine-nginx:amd64
  - docker push maurosoft1973/alpine-nginx:x86_64
  - docker push maurosoft1973/alpine-nginx